services:
  osx:
    image: sickcodes/docker-osx
    privileged: true
    devices: 
      - /dev/kvm
      - /dev/snd
    ports:
      - 50922:10022
    volumes:
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
      - /mnt/hdd/sync/gdrive:/mnt/hostshare
    environment:
      GENERATE_UNIQUE: true
      RAM: 16
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: "${WAYLAND_DISPLAY:-wayland-0}"
      QT_QPA_PLATFORM: wayland
      GDK_BACKEND: wayland
      CLUTTER_BACKEND: wayland
      DISPLAY: ":1"
      CPU: Haswell-noTSX
      CPUID_FLAGS: 'kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on'
      SHORTNAME: ventura
      XDG_SESSION_TYPE: wayland
      SIZE: 30G
      EXTRA: '-smp 16,sockets=8,cores=2 -virtfs local,path=/mnt/hostshare,mount_tag=hostshare,security_model=passthrough,id=hostshare'
volumes:
  docker-osx_data:
    name: docker-osx_data
